services:
    # image project
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - micro_emitente

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8002:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - micro_emitente

    
    pgsql:
        image: 'postgres:13'
        ports:
            - '${FORWARD_DB_PORT:-5502}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
              - ".:/var/www/html"
        networks:
            - micro_emitente
        healthcheck:
            test: [ "CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}" ]
            retries: 3
            timeout: 5s

  

    # queue
    queue:
        image: especializati/laravel9-app
        restart: unless-stopped
        command: "php artisan queue:work"
        volumes:
            - ./:/var/www
        depends_on:
            - redis
            - app
        networks:
            - micro_emitente

    # redis
    redis:
        image: redis:latest
        networks:
            - micro_emitente

networks:
    micro_emitente:
        name:   micro_emitente
        driver: bridge
